# This is a template for a GitHub Actions workflow.
# Copy this file to your project's .github/workflows/ directory (e.g., .github/workflows/main.yml)
# to enable automated testing and merging of AI-generated pull requests.

name: CI and Automerge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    # This job runs tests on the code.
    # Customize the steps below to match your project's setup.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify your project's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Or your project's dependency command

      - name: Run tests
        run: |
          # Replace 'pytest' with your project's actual test command
          pytest

  automerge:
    needs: test
    runs-on: ubuntu-latest
    # This job automatically merges the PR if the 'test' job passes.
    # It only runs on PRs created by the AI agent (assuming a specific branch prefix).
    if: success() && startsWith(github.head_ref, 'ai-dev/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge Pull Request
        run: |
          gh pr merge --auto --merge --delete-branch "$PR_URL"
        env:
          # The GITHUB_TOKEN is automatically provided by GitHub Actions.
          # You may need to grant it write permissions in your repository settings
          # under "Settings > Actions > General > Workflow permissions".
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Comment on PR
        run: |
          gh pr comment "$PR_URL" --body "Tests passed. Merging automatically. Great work, AI!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
